"""
components/report_download.py
Download Report page — TXT and JSON export of the full health report.
"""

import streamlit as st
import json
from datetime import datetime


def _build_txt_report(agent_results: dict, consensus: str, lifestyle: str, score: int) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "=" * 70,
        "  PERSONAL HEALTH DIAGNOSTIC REPORT",
        f"  Generated by HealthAI on {ts}",
        "=" * 70,
        "",
        f"  Overall Health Score: {score} / 100",
        "",
    ]
    lines += ["=" * 70, "  SPECIALIST ASSESSMENTS", "=" * 70, ""]
    for spec, report in agent_results.items():
        lines += [f"\n{spec.upper()}", "-" * 70, report, ""]

    lines += ["", "=" * 70, "  MULTIDISCIPLINARY CONSENSUS", "=" * 70, "", consensus, ""]

    if lifestyle:
        lines += ["", "=" * 70, "  PERSONALISED LIFESTYLE PLAN", "=" * 70, "", lifestyle, ""]

    lines += ["", "=" * 70, "  DISCLAIMER", "=" * 70,
              "This report is generated by AI and is not a substitute for",
              "professional medical advice. Always consult a qualified doctor.", ""]
    return "\n".join(lines)


def _build_json_report(agent_results: dict, consensus: str, lifestyle: str, score: int) -> str:
    payload = {
        "generated_at": datetime.now().isoformat(),
        "health_score": score,
        "specialist_reports": agent_results,
        "consensus_diagnosis": consensus,
        "lifestyle_plan": lifestyle,
        "disclaimer": "AI-generated. Not a substitute for professional medical advice.",
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)


def render_report_download():
    """Render the Download Report page."""
    st.markdown('<div class="page-title">📄 Download Your Report</div>', unsafe_allow_html=True)
    st.markdown('<div class="page-subtitle">Export your full AI health analysis as a formatted report.</div>', unsafe_allow_html=True)
    st.markdown('<hr class="custom-divider">', unsafe_allow_html=True)

    consensus = st.session_state.get("consensus_diagnosis")
    if not consensus:
        st.info("📤 No analysis yet. Go to **Upload Report** first.")
        return

    agent_results = st.session_state.get("agent_results", {})
    lifestyle     = st.session_state.get("lifestyle_plan", "")
    score         = st.session_state.get("health_score", 72)
    ts            = datetime.now().strftime("%Y%m%d_%H%M%S")

    txt_report  = _build_txt_report(agent_results, consensus, lifestyle, score)
    json_report = _build_json_report(agent_results, consensus, lifestyle, score)

    # Preview card
    st.markdown("""
    <div class="glass-card" style="text-align:center;padding:2rem;">
        <div style="font-size:3rem;">📑</div>
        <div style="font-weight:700;font-size:1.15rem;color:#e2e8f0;margin:.5rem 0 .3rem;">
            Your Health Report is Ready
        </div>
        <div style="color:#94a3b8;font-size:.9rem;max-width:400px;margin:0 auto;">
            Download your complete AI-generated health analysis including all specialist reports,
            consensus diagnosis, and lifestyle plan.
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown("""
        <div class="glass-card" style="text-align:center;">
            <div style="font-size:2rem;">📄</div>
            <div style="font-weight:600;color:#e2e8f0;margin:.3rem 0 .5rem;">Plain Text</div>
            <div style="color:#94a3b8;font-size:.82rem;">Human-readable format, great for printing or emailing your doctor.</div>
        </div>
        """, unsafe_allow_html=True)
        st.download_button(
            label="⬇️ Download TXT",
            data=txt_report,
            file_name=f"health_report_{ts}.txt",
            mime="text/plain",
            use_container_width=True,
        )

    with col2:
        st.markdown("""
        <div class="glass-card" style="text-align:center;">
            <div style="font-size:2rem;">🗂️</div>
            <div style="font-weight:600;color:#e2e8f0;margin:.3rem 0 .5rem;">JSON Data</div>
            <div style="color:#94a3b8;font-size:.82rem;">Structured data format, ideal for sharing with health apps or developers.</div>
        </div>
        """, unsafe_allow_html=True)
        st.download_button(
            label="⬇️ Download JSON",
            data=json_report,
            file_name=f"health_report_{ts}.json",
            mime="application/json",
            use_container_width=True,
        )

    with col3:
        st.markdown("""
        <div class="glass-card" style="text-align:center;opacity:.65;">
            <div style="font-size:2rem;">📊</div>
            <div style="font-weight:600;color:#e2e8f0;margin:.3rem 0 .5rem;">PDF Report</div>
            <div style="color:#94a3b8;font-size:.82rem;">Formatted PDF with charts and visual summaries.</div>
        </div>
        """, unsafe_allow_html=True)
        st.button("⬇️ Download PDF (coming soon)", use_container_width=True, disabled=True)

    st.markdown("---")

    # In-page preview
    with st.expander("👁️ Preview full text report"):
        st.text(txt_report[:3000] + ("\n…[truncated]" if len(txt_report) > 3000 else ""))

    st.caption("🔒 Your data is never stored on our servers. All analysis is performed in memory during your session.")
